### PR TITLE
docs: Add a README and reference the OpenAPI document

### PR DESCRIPTION
**Pull request by sameo**

### CODE REVIEW

**Comment by sameo** [comment]
cc @slp

**Comment by slp** [comment]
If we're moving `reference-kbs` here, it may be worth waiting a bit to avoid having to amend the link. Perhaps is also worth linking `kbs-types`?

**Comment by sameo** [comment]
@jialez0 Fixed and removed the reference-kbs link for now.

**Review by jialez0 — APPROVED** [review]
LGTM.

**Pull request merged**
