### PR TITLE
Recreate Cargo.lock file to retrieve latest AS

### PR DESCRIPTION
**Pull request by mkulke**
Since kbs references AS head, we just need to recreate a lock file

### CODE REVIEW

**Comment by surajssd** [comment]
cc: @Xynnn007 @jialez0 @sameo

**Comment by Xynnn007** [comment]
@mkulke Hey Magnus, could you help to check the error in e2e CI?

**Comment by mkulke** [comment]
> @mkulke Hey Magnus, could you help to check the error in e2e CI?

yup, I'll take a look. 

Something else, can we register a webhook on the kbs repo - so we can run e2e tests on an azure cvm runner?

**Comment by Xynnn007** [comment]
> > @mkulke Hey Magnus, could you help to check the error in e2e CI?
> 
> yup, I'll take a look.
> 
> Something else, can we register a webhook on the kbs repo - so we can run e2e tests on an azure cvm runner?

Sounds a good idea. Could you make an issue for this?

**Comment by Xynnn007** [comment]
> > @mkulke Hey Magnus, could you help to check the error in e2e CI?
> 
> @Xynnn007 PTAL #168
> 
> I'll rebase this then

Done

**Comment by mythi** [comment]
> Since kbs references AS head, we just need to recreate a lock file

Sort of related: I've been wondering if `coco-as-builtin` is the best choice as the default feature since it forces to install all the verifier dependencies.

**Pull request merged**
