### PR TITLE
bump: jsonwebtoken to 9

### PR DESCRIPTION
**Pull request by Xynnn007**
Close #289

### CODE REVIEW

**Comment by Xynnn007** [comment]
cc @mythi  Please check the Intel TA part if it is ok.

**Review by fitzthum — APPROVED** [review]
LGTM

**Comment by Xynnn007** [comment]
Rebased the latest code. cc @mythi for a double check.

**Review by mythi — APPROVED** [review]
LGTM

(sorry I had missed the earlier ping)

**Pull request merged**
