### PR TITLE
kbs: Update csv-rs dep to rev b74aa8c.

### PR DESCRIPTION
**Pull request by BaoshunFang**
1. Support more platform and launch API.
  2. Support openssl 3.2.0.

### CODE REVIEW

**Comment by BaoshunFang** [comment]
@jialez0 @Xynnn007 Please help to review the code.

**Comment by Xynnn007** [comment]
please change the rev inside client tool's Cargo.toml once guest components side pr is merged

**Review by fitzthum — APPROVED** [review]
LGTM, but see @Xynnn007's comment

**Comment by BaoshunFang** [comment]
> please change the rev inside client tool's Cargo.toml once guest components side pr is merged [confidential-containers/guest-components#448](https://github.com/confidential-containers/guest-components/pull/448)

Done

**Review by Xynnn007 — APPROVED** [review]
LGTM, thanks

**Pull request merged**
