### PR TITLE
Added e2e test for CoCo-AS using SNP evidence

### PR DESCRIPTION
**Pull request by Xynnn007**
Depends on #262 

Use a fixed ~~SGX~~ SNP evidence to test gRPC and RESTful CoCoAS to get token

### CODE REVIEW

**Comment by Xynnn007** [comment]
The error https://github.com/confidential-containers/kbs/actions/runs/7284163707/job/19849143732?pr=264 here is because PCCS cannot be connected (0xe019). I am not sure whether there is a accessable PCCS that is compatible with DCAP lib provided by Intel on GH Runner. Or we should use a self-hosted machine to run this test?

Hi @mkulke @jepio Could you give some comments?

**Comment by mkulke** [comment]
There should be a PCCS available in azure, but I doubt that works ootb on github runners. If that's the case, I would suggest a self-hosted runner. There is already an [open issue](https://github.com/confidential-containers/kbs/issues/223) for that. We could use the coco azure subscription to spawn ephemeral self-hosted runners that have access to the PCCS. Maybe we can look into that sometime early next year. We should be able to reuse the existing Garm setup from the infra repo.


https://learn.microsoft.com/en-us/azure/security/fundamentals/trusted-hardware-identity-management#how-do-i-use-intel-qpl-with-trusted-hardware-identity-management

**Comment by Xynnn007** [comment]
@mkulke Ok. I think the original aim of #223 is to generate the evidence in real TEE and do the verification. 
This PR only works for the second part, s.t. verify the evidence as a basic test case.

Let me try to change this PR into another platform test case like SNP which does not rely on the GH Runner env.

After this we can keep on #223

**Comment by Xynnn007** [comment]
Updated the code for easily support real TEE in future.

**Review by fitzthum — APPROVED** [review]
LGTM.

In the future maybe we can extend it to evaluate some policy as well. 

Also, if we use a self-hosted runner it shouldn't be too difficult to get some real evidence to use.

**Pull request merged**
