### PR TITLE
Merge Attestation-Service and KBS

### PR DESCRIPTION
**Pull request by Xynnn007**
follow https://github.com/confidential-containers/confidential-containers/issues/169

### CODE REVIEW

**Comment by Xynnn007** [comment]
Let's wait for the PR https://github.com/confidential-containers/guest-components/pull/388 to be merged and then continue with this PR.

**Comment by Xynnn007** [comment]
Things have been fixed:
- CODEOWNERS/LICENCE
- import relationship
- CI test

We still need the following things:
- wait for https://github.com/confidential-containers/guest-components/pull/388 and change rev for `kbs/tool`
- A new repo name
- fix the guides due to the new repo name

**Comment by mythi** [comment]
> follow [confidential-containers/confidential-containers#169](https://github.com/confidential-containers/confidential-containers/issues/169)

I've added my comments to the issue.

**Comment by fitzthum** [comment]
My vote for the name would be to simply stick with `kbs` for now. If we come up with a good name that covers all of the components we can change it later. So far I don't think we have a great alternative.

**Review by fitzthum — APPROVED** [review]
LGTM

**Comment by mythi** [comment]
> LGTM

@fitzthum did you follow to the conversation in the issue? There were objections to this change and now it's merged without a concensus.

**Comment by Xynnn007** [comment]
> > LGTM
> 
> @fitzthum did you follow to the conversation in the issue? There were objections to this change and now it's merged without a concensus.

@mythi 

I must have done something bad that click the rebase button before reaching a concensus with you. We can revert the merging if needed.

Also, a better way is that let's keep talking about that in the issue or in slack (I recommend) to reach a consensus.

**Comment by Xynnn007** [comment]
> > LGTM
> 
> @fitzthum did you follow to the conversation in the issue? There were objections to this change and now it's merged without a concensus.

@mythi 

I must have done something bad that click the rebase button before reaching a concensus with you. We can revert the merging if needed.

Also, a better way is that let's keep talking about that in the issue or in slack (I recommend) to reach a consensus.

**Pull request merged**
